#!/usr/bin/env bash

function bootstrap {
  local shome="${_fluentd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile bundler --local

  "$shome/script/update"
}

bootstrap "$@"
