#!/usr/bin/env bash

function main {
  local shome="${_fluentd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  mkdir -p "$shome/bin"
  (set +f; ln -nfs $shome/vendor/bundle/bin/fluent* "$shome/bin/")
}

main
