#!/usr/bin/env bash

function main {
  local shome="${_fluentd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  mkdir -p "$shome/bin"
  set +f
  for f in $shome/vendor/bundle/bin/fluent*; do
    if  [[ -x "$f" ]] ; then
      ln -nfs "$f" "$shome/bin/"
    fi
  done
  set -f
}

main
